// React
import { useState } from "react";

// Next
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// Components
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";
import EarnedCrypto from "@/components/EarnedCrypto";

// Images
import Ball1 from "@/public/features-ball-desktop.png";
import Ball2 from "@/public/landing-ball-desktop.png";
import Line from "@/public/line.png";
import CopyIcon from "@/public/copy-icon.png";

type DateElements = {
  type: string;
  year: number;
  month?: number;
  day?: number;
  hour?: number;
  minute?: number;
  second?: number;
};

const Airdrop = () => {
  const [isShowCopied, setIsShowCopied] = useState(false);

  const waitingDate: DateElements = {
    type: "start",
    year: 2024, // Year
    month: 0, // 1 => 12
    day: 0, // 1 => 31
    hour: 0, // 0 => 23
    minute: 0, // 0 => 59
    second: 0, // 0 => 59
  };

  let progress: number = 1000;
  let maxProgress: number = 3500;
  let progressPercentage: number = Math.floor((progress / maxProgress) * 100);

  let waitingDay =
    Date.UTC(
      waitingDate.year,
      waitingDate.month || 0,
      waitingDate.day || 1,
      waitingDate.hour || 0,
      waitingDate.minute || 0,
      waitingDate.second || 0
    ) /
    1000 /
    60 /
    60 /
    24;
  let dayNow = Date.now() / 1000 / 60 / 60 / 24;

  const waitingDays = waitingDay - dayNow;
  const waitingHours = (waitingDays - Math.floor(waitingDays)) * 24;
  const waitingMinutes = (waitingHours - Math.floor(waitingHours)) * 60;
  const waitingSeconds = (waitingMinutes - Math.floor(waitingMinutes)) * 60;

  const floorNumbers = (num: number) => {
    return Math.floor(num);
  };

  const handleCopiedMessage = () => {
    setIsShowCopied(true);
    setTimeout(() => {
      setIsShowCopied(false);
    }, 1_000);
  };

  return (
    <>
      <Head>
        <title>Airdrop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-icon.png" />
      </Head>
      <main className="bg-eerieBlack bg-repeat relative">
        <Header />
        <div className="content relative flex">
          {/* Start Side Bar */}
          <SideBar />
          {/* End Side Bar */}

          {/* Start Main Content */}
          <div className="main lg:w-4/5 px-5">
            <div className="text-honeydew">
              <h1 className="flex justify-center items-center py-10 font-semibold text-2xl">
                Reward Portal
              </h1>
              <div className="boxs flex flex-col justify-center items-center lg:flex-row gap-5 lg:h-[350px]">
                {/* Start Earned Crypto */}
                <EarnedCrypto />
                {/* End Earned Crypto */}

                <Image
                  src={Ball1}
                  alt="Ball 1"
                  className="hidden lg:block absolute z-[0] right-0 top-0 translate-y-[50%]"
                />
                <Image
                  src={Ball2}
                  alt="Ball 2"
                  width={250}
                  height={250}
                  className="hidden lg:block absolute z-[0] left-[-50px] top-[-100px]"
                />
              </div>
              {/* Start Sale */}
              <div className="sale w-full lg:w-2/3 mx-auto p-5 my-10 relative z-[3] rounded-lg border-t-[3px] border-t-electricGreen bg-[#202020CC]">
                {/* Start Contribute */}
                <div className="contribute flex flex-col gap-5 text-sm lg:text-md">
                  <div className="balance flex gap-5">
                    <div className="w-3/4 flex flex-col gap-2">
                      <label htmlFor="balance-input">Balance</label>
                      <input
                        type="number"
                        placeholder="0.00"
                        className="py-2 rounded-lg indent-3 bg-[#4D4D4D] text-honeydew focus:outline-none"
                      />
                    </div>
                    <div className="w-1/4 flex flex-col gap-2">
                      <label htmlFor="balance-currency">Currency</label>
                      <select
                        name="balance-currency"
                        id="balance-currency"
                        className="relative bg-[#4D4D4D] focus:border-none focus:outline-none rounded-lg flex justify-between items-center gap-5 px-5 py-3"
                      >
                        <option value="bnb">BNB</option>
                        {/* <Image
                          src={ArrowDown}
                          alt="Arrow Down"
                          className="absolute top-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%]"
                        /> */}
                      </select>
                    </div>
                  </div>
                  <div className="estimated flex gap-5">
                    <div className="w-3/4 flex flex-col gap-2">
                      <label htmlFor="estimated-input">To (estimated)</label>
                      <input
                        type="number"
                        placeholder="0.00"
                        className="py-2 rounded-lg indent-3 bg-[#4D4D4D] text-honeydew focus:outline-none"
                      />
                    </div>
                    <div className="w-1/4 flex flex-col gap-2">
                      <label htmlFor="estimated-currency">Currency</label>
                      <select
                        name="estimated-currency"
                        id="estimated-currency"
                        className="relative bg-[#4D4D4D] focus:border-none focus:outline-none rounded-lg flex justify-between items-center gap-5 px-5 py-3"
                      >
                        <option value="FTC">$FTC</option>
                        {/* <Image
                          src={ArrowDown}
                          alt="Arrow Down"
                          className="absolute top-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%]"
                        /> */}
                      </select>
                    </div>
                  </div>
                  <button className="btn w-min mx-auto rounded-lg hover:opacity-50 py-2 px-5 my-3 bg-[#09DB04] text-[#463399]">
                    Contribute
                  </button>
                </div>
                {/* End Contribute */}

                {/* Start Progress */}
                <div className="progress">
                  <div className="line relative w-full">
                    <h5 className="mb-2">Progress</h5>
                    <div className="w-full bg-[#566156] h-[15px] rounded relative">
                      <span
                        className="rounded h-[15px] absolute top-0 left-0 bg-electricGreen"
                        style={{ width: `${progressPercentage}%` }}
                      ></span>
                    </div>
                    <div className="min-max flex justify-between items-center w-full px-1 py-1 text-sm">
                      <div className="min">0.05 BNB</div>
                      <div className="max">{maxProgress} BNB</div>
                    </div>
                  </div>
                  <div className="details py-5 mx-auto flex justify-center items-center">
                    <div>
                      <p>Minimum Contribution: 0.1 BNB</p>
                      <p>Maximum Contribution: 25.0 BNB</p>
                      <p>Soft Cap: 1500.0 BNB</p>
                      <p>Hard Cap: 3500.0 BNB</p>
                    </div>
                  </div>
                </div>
                {/* End Progress */}

                {/* Start Sale Time */}
                <div className="sale-time text-center flex-col gap-7">
                  <div className="before flex flex-col gap-3">
                    <h4>Time before sale starts</h4>
                    <div className="bg-[#323232] border-[#A1A1A1] border-[1px] rounded-lg text-honeydew flex justify-center items-center gap-3 lg:gap-5 py-5 px-1">
                      <div className="days">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          00
                        </div>
                        <p className="text-md lg:text-lg capitalize">Days</p>
                      </div>
                      <span>:</span>
                      <div className="hours">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          00
                        </div>
                        <p className="text-md lg:text-lg capitalize">Hours</p>
                      </div>
                      <span>:</span>
                      <div className="minutes">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          00
                        </div>
                        <p className="text-md lg:text-lg capitalize">Minutes</p>
                      </div>
                      <span>:</span>
                      <div className="seconds">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          00
                        </div>
                        <p className="text-md lg:text-lg capitalize">Seconds</p>
                      </div>
                    </div>
                  </div>
                  <div className="my-5 after flex flex-col gap-3">
                    <h4>Time before sale ends</h4>
                    <div className="bg-[#121215] rounded-lg border-[1px] border-[#99FF99] text-[#99FF99] flex justify-center items-center gap-3 lg:gap-5 py-5 px-1">
                      <div className="days">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          240
                        </div>
                        <p className="text-md lg:text-lg capitalize">Days</p>
                      </div>
                      <span>:</span>
                      <div className="hours">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          06
                        </div>
                        <p className="text-md lg:text-lg capitalize">Hours</p>
                      </div>
                      <span>:</span>
                      <div className="minutes">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          29
                        </div>
                        <p className="text-md lg:text-lg capitalize">Minutes</p>
                      </div>
                      <span>:</span>
                      <div className="seconds">
                        <div className="num text-xl lg:text-2xl tracking-widest">
                          14
                        </div>
                        <p className="text-md lg:text-lg capitalize">Seconds</p>
                      </div>
                    </div>
                  </div>
                </div>
                {/* End Sale Time */}

                {/* Start Track Your Referrals */}
                <div className="track-your-referrals text-center text-honeydew lg:w-1/2 mx-auto py-10 flex flex-col gap-4">
                  <h3 className="text-2xl">Track your referrals</h3>
                  <p>
                    Visit the referral page{" "}
                    <Link
                      href="/referrals"
                      className="text-electricGreen uppercase underline"
                    >
                      HERE
                    </Link>{" "}
                    or paste your referral’s wallet address to see if they
                    already participated in $FTC Presale Event
                  </p>
                </div>
                {/* End Track Your Referrals */}

                {/* Start Wallet Address */}
                <div className="wallet-address lg:w-1/2 mx-auto flex flex-col gap-2 mb-5">
                  <h4>Wallet address</h4>
                  <input
                    type="text"
                    placeholder="Paste wallet address"
                    className="indent-4 py-3 w-full rounded-lg bg-[#4D4D4D] placeholder:text-honeydew placeholder:tracking-wide placeholder:text-lg text-lg text-honeydew tracking-wide focus:outline-none"
                  />
                </div>
                {/* End Wallet Address */}
              </div>
              {/* End Sale */}

              {/* Start Airdrop Special Offer */}
              <div className="airdrop-special-offer w-full lg:w-2/3 mx-auto p-5 my-10 relative z-[3] rounded-lg border-t-[3px] border-t-electricGreen bg-gradient-to-b from-[#1F1F1FB2] to-[#033C01B2] text-center flex flex-col justify-between items-center gap-5 text-honeydew">
                <h3 className="py-3 text-xl">Fratun Airdrop Special Offer!</h3>
                <p>
                  {" "}
                  Invite Your Friends and Earn FTC Coins + USDT0.25 USDT + 510
                  FTC
                </p>
                <button className="bg-transparent w-full lg:w-auto text-[#99FF99] border-[1px] border-[#99FF99] py-2 px-10 rounded-lg hover:bg-[#99FF99] hover:text-[#463399] duration-300">
                  Invite now!
                </button>
              </div>
              {/* End Airdrop Special Offer */}

              {/* Start Pre-Sale Rules */}
              <div className="pre-sale-rules w-full lg:w-2/3 mx-auto px-10 py-5 my-10 relative z-[3] rounded-lg border-t-[3px] border-t-electricGreen bg-gradient-to-b from-[#1F1F1FB2] to-[#033C01B2] text-honeydew">
                <h4 className="capitalize text-lg my-4">Pre-sale Rules</h4>
                <p>
                  Pre-sale Rules There is going to be an ICO offer on FRATUN
                  COIN which is just to raise some BNB which will make you
                  accumulate a little more FRATUN Coins while the offer last and
                  we will use 100% of the money raised during the ICO for the
                  LIQUIDITY.PRESALE/ICO DETAILSa.
                  <br /> <br />​ FRATUN COIN presale is in five (5) phases with
                  each stages having 14,000,000 coins each
                </p>
              </div>
              {/* End Pre-Sale Rules */}

              {/* Start Stages */}
              <div className="stages w-full lg:w-2/3 mx-auto relative z-[3] flex lg:block flex-col gap-3">
                <div className="w-full flex gap-3 lg:gap-4 lg:h-[300px] items-center relative z-[4] flex-col lg:flex-row">
                  <div className="stage w-full h-[140px] p-3 border-t-[3px] border-t-[#F1E806] bg-gradient-to-b from-[#1F1F1FE5] to-[#282401E5] text-honeydew lg:w-1/3 rounded-lg lg:translate-y-[-75px]">
                    <h2 className="my-3 text-2xl text-center">Stage 1</h2>
                    <p className="uppercase text-lg text-center lg:text-start">
                      1 Fratun COIN = 0.00005 BNB
                    </p>
                  </div>
                  <div className="stage w-full h-[140px] p-3 border-t-[3px] border-t-[#F1E806] bg-gradient-to-b from-[#1F1F1FE5] to-[#282401E5] text-honeydew lg:w-1/3 rounded-lg">
                    <h2 className="my-3 text-2xl text-center">Stage 2</h2>
                    <p className="uppercase text-lg text-center lg:text-start">
                      1 Fratun COIN = 0.000075 BNB
                    </p>
                  </div>
                  <div className="stage w-full h-[140px] p-3 border-t-[3px] border-t-[#F1E806] bg-gradient-to-b from-[#1F1F1FE5] to-[#282401E5] text-honeydew lg:w-1/3 rounded-lg lg:translate-y-[75px]">
                    <h2 className="my-3 text-2xl text-center">Stage 3</h2>
                    <p className="uppercase text-lg text-center lg:text-start">
                      1 Fratun COIN = 0.0001 BNB
                    </p>
                  </div>
                </div>
                <div className="w-full flex gap-3 lg:gap-[150px] lg:h-[300px] justify-center items-center relative z-[4] lg:my-20 flex-col lg:flex-row">
                  <div className="stage w-full h-[140px] p-3 border-t-[3px] border-t-[#F1E806] bg-gradient-to-b from-[#1F1F1FE5] to-[#282401E5] text-honeydew lg:w-1/3 rounded-lg lg:translate-y-[-75px]">
                    <h2 className="my-3 text-2xl text-center">Stage 4</h2>
                    <p className="uppercase text-lg text-center lg:text-start">
                      1 Fratun COIN = 0.000125 BNB
                    </p>
                  </div>
                  <div className="stage w-full h-[140px] p-3 border-t-[3px] border-t-[#F1E806] bg-gradient-to-b from-[#1F1F1FE5] to-[#282401E5] text-honeydew lg:w-1/3 rounded-lg">
                    <h2 className="my-3 text-2xl text-center">Stage 5</h2>
                    <p className="uppercase text-lg text-center lg:text-start">
                      1 Fratun COIN = 0.00015 BNB
                    </p>
                  </div>
                </div>
                <Image
                  src={Line}
                  alt="Line 1"
                  className="absolute top-[75px] left-[50%] translate-x-[-50%] h-[460px] hidden lg:block"
                />
              </div>
              {/* End Stages */}

              {/* Start Purpose */}
              <div className="purpose w-full lg:w-2/3 mx-auto p-8 bg-gradient-to-b rounded-lg from-[#1F1F1FB2] to-[#033C01B2] border-t-[3px] border-t-electricGreen my-10 text-center flex flex-col justify-between items-center gap-5">
                <p className="text-lg">
                  These values are strictly for the PRESALE period till we
                  exhaust the total 70,000,000 set aside for this purpose.
                </p>
                <div className="values flex flex-col gap-3 f">
                  <p>​Minimum Buy: 0.1 BNB</p>
                  <p>Maximum Buy: 25 BNB</p>
                  <p>​Soft Cap: 1,500 BNB</p>
                  <p>Hard Cap: 3,500 BNB</p>
                </div>
              </div>
              {/* End Purpose */}

              {/* Start Note */}
              <div className="note w-full lg:w-2/3 mx-auto p-8 bg-gradient-to-b border-t-[3px] rounded-lg border-t-electricGreen from-[#1F1F1FB2] to-[#033C01B2] flex flex-col gap-4 my-10">
                <p>
                  Listing price immediately the PRESALE end: 0.0009 BNB per
                  FRATUN COIN which is well over 2000% gain already.
                </p>
                <p>
                  And also because FRATUN Coin is an utility token its daily
                  usability will make the price skyrocket after our Social Media
                  Platform is launched.
                </p>
                <p>
                  Pre-sale price is 1 BNB = 20,000 FTC. The minimum purchase is
                  0.1 BNB, and the maximum purchase is 25 BNB.
                </p>
                <p>
                  There are two distinct ways you can participate in FRATUN
                  PRESALE offer.
                </p>
                <ul className="list-decimal pl-4 flex flex-col gap-2">
                  <li>
                    Send BNB from your wallet to the pre-sale contract address.
                    Our system will automatically send FTC tokens to your wallet
                    instantly. You can send BNB of any amount from 0.1 to 25
                    then get the FTC equivalent.
                  </li>
                  <p>Or</p>
                  <li>
                    Visit the Presale page https://presale.fratun.com in your
                    browser
                  </li>
                </ul>
                <ul className="list-disc pl-4 flex flex-col gap-2">
                  <li>
                    Connect your trust wallet through wallet connect After
                    successful wallet connect
                  </li>
                  <li>
                    input the amount of BNB you wish to use to partake in the
                    ICO then submit then confirm the transaction then you have
                    the FTC equivalent of whatsoever amount of BNB you have
                    committed.
                  </li>
                </ul>
              </div>
              {/* End Note */}

              {/* Start Presale Live */}
              <div className="presale-live-btn my-5 w-2/3 mx-auto flex justify-center items-center">
                <button className="px-5 py-2 bg-electricGreen text-[#463399] rounded-lg hover:opacity-50 duration-300">
                  Presale Live!
                </button>
              </div>
              {/* End Presale Live */}

              {/* Start Presale Contract Address */}
              <div className="presale-contract-address bg-[#2E2E2ECC] border-t-[3px] border-t-electricGreen rounded-lg w-full lg:w-1/2 flex justify-between items-center p-5 mx-auto my-10">
                <div className="text flex flex-col gap-3">
                  <h5 className="font-semibold">Presale Contract Address</h5>
                  {/* Redux Context */}
                  <p className="text-[10px] lg:text-[16px]">
                    0x68A46444E19B57B30D2e30E9fd483A56Bc60Ed49
                  </p>
                </div>
                <Image
                  src={CopyIcon}
                  alt="Copy Icon"
                  className="cursor-pointer"
                  onClick={handleCopiedMessage}
                />
              </div>
              {/* End Presale Contract Address */}

              {/* Start Presale Price */}
              <div className="presale-price p-8 w-full lg:w-2/3 mx-auto bg-gradient-to-b from-[#1F1F1FB2] to-[#033C01B2] rounded-lg border-t-[3px] border-t-electricGreen my-10 flex flex-col gap-5">
                <p>Pre-sale price: 1 BNB = 20,000 FTC</p>
                <p>
                  The minimum purchase is 0.1 BNB, and the maximum purchase is
                  25 BNB.
                </p>
                <p>
                  Send BNB from your wallet to the pre-sale contract address
                  above. Our system will send FTC coins equivalent to your
                  wallet instantly.
                </p>
              </div>
              {/* End Presale Price */}
            </div>
          </div>
          {/* End Main Content */}
        </div>
        <Footer />
        {/* Start Copied Message */}
        <div
          className={`copied-message flex justify-center items-center bg-gradient-to-r from-[#1F1F1FB2] to-[#033C01B2] text-honeydew p-3 text-lg fixed left-[50%] translate-x-[-50%] z-[99] duration-300 rounded-lg border bottom-[53px] ${
            isShowCopied ? "" : "hidden"
          }`}
        >
          Copied!
        </div>
        {/* Start Copied Message */}
      </main>
    </>
  );
};

export default Airdrop;
