// React
import { useState, useEffect } from "react";

// Next
import Head from "next/head";
import Link from "next/link";

// Components
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";

const Referrals = () => {
  const [screenWidth, setScreenWidth] = useState("loading");

  useEffect(() => {
    innerWidth >= 768 ? setScreenWidth("desktop") : setScreenWidth("mobile");
  }, []);

  return (
    <>
      <Head>
        <title>Referrals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-icon.png" />
      </Head>
      <main className="bg-eerieBlack bg-repeat relative">
        <Header />
        <div className="content relative flex">
          <SideBar />
          <div className="main px-5 lg:4/5">
            <h1 className="text-4xl my-20 text-honeydew text-center">
              Referrals
            </h1>
            {/* Start Airdrop Special Offers */}
            <div className="airdrop-special-offers w-full lg:w-2/3 mx-auto bg-[#202020CC] border-t-[3px] border-t-electricGreen text-honeydew rounded-lg p-5 lg:p-10 flex flex-col justify-between items-center gap-10">
              <h2 className="text-2xl text-center">
                Fratun Airdrop Special Offer!
              </h2>
              <div className="invite-friend">
                <p className="text-center mb-5 w-2/3 mx-auto">
                  Invite Your Friends and Earn FTC Coins + USDT0.25 USDT + 510
                  FTC
                </p>
                <div className="link bg-[#121215] border-[1px] border-[#99FF99] rounded-lg p-5 flex flex-col justify-center items-center gap-5">
                  <h4 className="text-xl">Your Referral Link</h4>
                  <Link
                    href="https://link.ftc.com/register?refCode=5GHAJD"
                    className="text-[#99FF99] text-lg"
                  >
                    https://link.ftc.com/register?refCode=5GHAJD
                  </Link>
                </div>
              </div>
              <ul className="list-disc pl-5">
                <li className="my-4">
                  Invite your friends and families earn 510 FTC Coins + 0.25
                  USDT and get ahead of others!
                </li>
                <li className="my-4">
                  When you refer anyone and such person has performed the
                  necessary tasks and claim our free airdrop then on such person
                  you will be rewarded with 0.25 USDT &amp; 510 FTC.
                </li>
                <li className="my-4">
                  You get extra 5% on any amount of BNB spent by those you refer
                  if they partake in our PRESALE/ICO offer.
                </li>
                <li className="my-4">
                  You can refer unlimited numbers of persons and accumulating
                  USDT with FTC.
                </li>
              </ul>
            </div>
            {/* End Airdrop Special Offers */}

            {/* Start Table */}
            {screenWidth === "desktop" ? (
              <table className="flex flex-col bg-[#202020CC] w-2/3 mx-auto border-t-[3px] border-t-electricGreen my-10 rounded-lg text-honeydew text-center">
                <thead className="w-full h-full flex">
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <th className="border-[#2F4A3B] p-3 border rounded-tl-lg">
                      S/N
                    </th>
                    <th className="border-[#2F4A3B] p-3 border">BNB Wallet</th>
                    <th className="border-[#2F4A3B] p-3 border">Airdrop</th>
                    <th className="border-[#2F4A3B] p-3 border">Purchase</th>
                    <th className="border-[#2F4A3B] p-3 border rounded-tr-lg">
                      Referral
                    </th>
                  </tr>
                </thead>
                <tbody className="w-full h-full flex flex-col">
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px] inline-block w-full h-full"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]">
                      Claimed/ Not yet
                    </td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]">
                      Bought/ Not yet
                    </td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]">
                      Only People referred and claimed airdrop
                    </td>
                  </tr>
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                  </tr>
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                  </tr>
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                  </tr>
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                  </tr>
                  <tr className="w-full grid grid-cols-5 grid-rows-1">
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px] rounded-bl-lg"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    <td className="border-[#2F4A3B] border p-3 min-h-[50px] rounded-br-lg"></td>
                  </tr>
                </tbody>
              </table>
            ) : (
              <>
                <table className="flex flex-col bg-[#202020CC] w-full mx-auto border-t-[3px] border-t-electricGreen my-10 rounded-lg text-honeydew text-center">
                  <thead className="w-full h-full flex">
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <th className="border-[#2F4A3B] p-3 border rounded-tl-lg">
                        S/N
                      </th>
                      <th className="border-[#2F4A3B] p-3 border">
                        BNB Wallet
                      </th>
                      <th className="border-[#2F4A3B] p-3 border border-tr-lg">
                        Airdrop
                      </th>
                    </tr>
                  </thead>
                  <tbody className="w-full h-full flex flex-col">
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px] inline-block w-full h-full"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]">
                        Claimed/ Not yet
                      </td>
                    </tr>
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>

                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>

                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>

                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-3 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px] rounded-bl-lg"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>

                      <td className="border-[#2F4A3B] border p-3 min-h-[50px] rounded-br-lg"></td>
                    </tr>
                  </tbody>
                </table>
                <table className="flex flex-col bg-[#202020CC] w-full mx-auto border-t-[3px] border-t-electricGreen my-10 rounded-lg text-honeydew text-center">
                  <thead className="w-full h-full flex">
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <th className="border-[#2F4A3B] p-3 border rounded-tl-lg">
                        Purchase
                      </th>
                      <th className="border-[#2F4A3B] p-3 border rounded-tr-lg">
                        Referral
                      </th>
                    </tr>
                  </thead>
                  <tbody className="w-full h-full flex flex-col">
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]">
                        Bought/ Not yet
                      </td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]">
                        Only People referred and claimed airdrop
                      </td>
                    </tr>
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px]"></td>
                    </tr>
                    <tr className="w-full grid grid-cols-2 grid-rows-1">
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px] rounded-bl-lg"></td>
                      <td className="border-[#2F4A3B] border p-3 min-h-[50px] rounded-br-lg"></td>
                    </tr>
                  </tbody>
                </table>
              </>
            )}
            {/* End Table */}
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Referrals;
